#! /usr/bin/env node

const { execSync } = require('node:child_process')

try {
  execSync("fcitx5-remote -t").toString()
  const currentInputMethod = execSync("fcitx5-remote -n").toString().trim()
  execSync(`notify-send -t 500 input ${currentInputMethod}`)
} catch (err) {
  execSync(`notify-send input 'Cannot switch input method: ${err.message}'`)
}
