#!/usr/bin/env node
const { formatEventTitle } = require('./calendar-utils')
const { execSync } = require('node:child_process')

try {
  const events = execSync("khal list now eod")
    .toString()

  let nextEvents = formatEventTitle(events).split('\n').slice(1).map(event => {
    const title = event.length > 50 ? event.slice(0, 35) : event
    return title
  })

  nextEvents = Array.from(new Set(nextEvents)).join(" | ") || ''

  nextEvents = nextEvents.length ? "󱑑 ".concat(nextEvents): "󱑑 [No event for today]"

  const payload = { text: nextEvents, tooltip: "" }
  console.log(JSON.stringify(payload))
} catch (err) {
  execSync(`notify-send input 'Cannot run khal-script: ${err.message}'`)
}
