#!/usr/bin/env node

/** biome-ignore-all lint/suspicious/noConsole: really need this */
const { execSync } = require('node:child_process')

try {
  const events = execSync("khal list now 1d --format '{title} {start-time}-{end-time}'")
    .toString().trim()

  const nextEvents = events.split('\n').slice(1, 3).map(event => `[${event}]`).join("   ") || ''

  const payload = { text: nextEvents, tooltip: events }
  console.log(JSON.stringify(payload))
} catch (err) {
  execSync(`notify-send input 'Cannot run khal-script: ${err.message}'`)
}
