#!/usr/bin/env node
const { writeFileSync } = require('node:fs')
const configs = ["abd", "aa"]
const source = require('./base.json')
const customKeyMaps = JSON.parse(JSON.stringify(source.customKeyMaps))
delete source.customKeyMaps

configs.forEach(workspace => {
  const filename = `${workspace}.json`
  const keymaps = customKeyMaps[workspace] || []

  delete source.customKeyMaps

  writeFileSync(filename, JSON.stringify({
    ...source,
    keyMappings: [
      ...source.keyMappings,
      ...keymaps
    ]
  }, null, 2))
})

console.log('Done!')
