# Extra env variables
env = TERMINAL,       wezterm
env = BROWSER,        brave
env = EDITOR,         neovide
env = XCURSOR_SIZE,   21

# NVIDIA hybrid GPU (Intel Iris Xe + RTX 2050)
env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
