# Extra env variables
env = TERMINAL,       kitty
env = BROWSER,        brave
env = EDITOR,         neovide
env = SHELL,          /usr/bin/zsh
env = XCURSOR_SIZE,   21

# NVIDIA hybrid GPU (Intel Iris Xe + RTX 2050)
env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
env = WLR_NO_HARDWARE_CURSORS,1
