general {
    lock_cmd = omarchy-lock-screen
    before_sleep_cmd = hubstaff stop
    after_sleep_cmd = hyprctl dispatch dpms on
    inhibit_sleep = 0
}

# Lock screen after 16 minutes (960s)
listener {
    timeout = 960
    on-timeout = loginctl lock-session
}

# Suspend after 17 minutes (1020s)
listener {
    timeout = 1020
    on-timeout = systemctl suspend
}
