# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    border_size = 0
    gaps_in = 0
    gaps_out = 0
    layout = monocle
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 4
    active_opacity = 1
    inactive_opacity = 1
    fullscreen_opacity = 1
    dim_inactive = true
    dim_strength = 0.2
}

# https://wiki.hyprland.org/Configuring/Master-Layout/
master {
    # Max-like layout similar to qtile
    orientation = center
    new_on_top = true
    new_status = master
    mfact = 0.5
}

misc {
    key_press_enables_dpms = true
    exit_window_retains_fullscreen = true
}

ecosystem {
    no_update_news = true
    no_donation_nag = true
  }

# Add any other personal Hyprland configuration below
windowrule = match:class org.pulseaudio.pavucontrol, float on, size monitor_w*0.75 monitor_h*0.8
windowrule = match:class Netsoft-com.netsoft.hubstaff, size 340 160, move monitor_w-340 monitor_h-160
