#!/bin/bash

current=$(ibus engine)

if [[ "$current" == *"Bamboo"* ]]; then
  ibus engine "xkb:us::eng"
  setxkbmap -variant colemak
  notify-send -t 1000 "Input: US Colemak"
else
  ibus engine "Bamboo"
  notify-send -t 1000 "Input: VI Bamboo"
fi
