#!/usr/bin/python3

import subprocess

cmd = subprocess.run('setxkbmap -query', shell=True,capture_output=True,text=True)
variant='colemak'

if variant in cmd.stdout:
    variant='intl'

subprocess.Popen(['setxkbmap', '-variant', variant])
subprocess.Popen(['notify-send', 'Setxkbmap', f'Variant: {variant}', '-t', '1000'])
