local map = require('base.utils').map

map('n', 'gg', '<Nop>')
map('n', 'g%', '<Nop>')
map('n', 'gqq', '<Nop>')
map('n', 'gq', '<Nop>')
map('n', 'gT', '<Nop>')
map('n', 'gt', '<Nop>')
map('n', 'gj', '<Nop>')
map('n', 'gk', '<Nop>')
map('n', 'g$', '<Nop>')
map('n', 'g0', '<Nop>')
map('n', 'gH', '<Nop>')
map('n', 'gD', '<Nop>')
map('n', 'gF', '<Nop>')
map('n', 'gd', '<Nop>')
map('n', 'gf', '<Nop>')
map('n', 'gh', '<Nop>')
map('n', 'gO', '<Nop>')
map('n', 'gri', '<Nop>')
map('n', 'grt', '<Nop>')
map('n', 'grr', '<Nop>')
map('n', 'gra', '<Nop>')
map('n', 'grn', '<Nop>')
map('n', 'gcc', '<Nop>')
map('n', 'gc', '<Nop>')
map('n', 'gx', '<Nop>')