local color = require("config/color")

local hi = {
  black = "${black}",
  cyan = "${cyan}",
  yellow = "${yellow}",
  orange = "${orange}",
  white = "${white}",
  purple = "${purple}",
  blue = "${blue}",
  red = "${red}",
  light_red = "${light_red}",
  green = "${green}",
  gray = "${gray}",
  dark_gray = "${dark_gray}",
  cursorline = "${cursorline}",
  comment = "${comment}",
}

return {
  {
    "olimorris/onedarkpro.nvim",
    config = function()
      require("onedarkpro").setup({
        colors = {
          gray = color.gray,
          blue = color.blue,
          cyan = color.cyan,
          black = color.black,
          orange = color.orange,
          white = color.white,
          purple = color.purple,
          yellow = color.yellow,
          red = color.red,
          light_red = color.light_red,
          green = color.green,
          float_bg = color.black,
          bg_statusline = color.black,
          bg = color.black,
          comment = color.gray,
          git_add = color.green,
          git_change = color.orange,
          git_delete = color.red,
          git_hunk_add = color.green,
          git_hunk_delete = color.red,
          diff_delete = color.red,
          highlight = color.orange,
          git_hunk_delete_inline = color.red,
          virtual_text_hint = color.cyan,
          virtual_text_error = color.red,
          diff_text = color.green,
          virtual_text_warning = color.yellow,
          virtual_text_information = color.blue,
          cursorline = color.dark_gray,
          selection = "#2e2e2e",
          color_column = "#232323",
          fold = "#1f1f1f",
          git_hunk_add_inline = "#3f534f",
          diff_add = "#003e4a",
          fg_gutter_inactive = "#abb2bf",
          fg = "#abb2bf",
          git_hunk_change_inline = "#41483d",
          line_number = "#495162",
          inlay_hint = "#33373e",
          indentline = "#2c2c2c",
          fg_gutter = "#252525",
        },
        highlights = {
          ["@punctuation.delimiter"] = { fg = hi.yellow },
          ["@punctuation.special"] = { fg = hi.blue },
          ["@punctuation.bracket"] = { fg = hi.yellow },
          ["@operator"] = { fg = hi.yellow },
          DiagnosticUnderlineError = { underline = true },
          DiagnosticUnderlineInfo = { underline = true },
          DiagnosticUnderlineWarn = { underline = true },
          DiagnosticUnderlineHint = { underline = true },
          Visual = { bg = hi.blue, fg = hi.black },
          CursorLineNr = { fg = hi.blue, bold = true, bg = hi.cursorline },
          CursorColumn = { bg = hi.cursorline },
          IblWhitespace = { fg = hi.cursorline },
          WinSeparator = { fg = hi.blue },
          -- gitsign & diffview
          GitSignsCurrentLineBlame = { bg = hi.cursorline, fg = hi.comment },
          DiffviewDiffDelete = { bg = hi.light_red },
          -- flash.nvim
          FlashLabel = { fg = hi.blue, bg = hi.black, italic = true },
          FlashMatch = { fg = hi.gray, bg = hi.black },
          FlashCurrent = { fg = hi.red, bg = hi.black, underline = true },
          FlashBackdrop = { fg = hi.gray, bg = hi.black },
          -- snacks
          SnacksIndent = { fg = hi.gray },
          SnacksIndentScope = { fg = hi.white },
          -- grugfar
          GrugFarResultsMatch = { bg = hi.gray, fg = hi.blue },
          GrugFarResultsPath = { fg = hi.red, underline = true, italic = true },
        },
        options = {
          cursorline = true,
          transparency = true,
          terminal_colors = true,
          lualine_transparency = true,
          highlight_inactive_windows = true,
        },
      })
    end,
  },
  {
    "LazyVim/LazyVim",
    keys = false,
    opts = {
      colorscheme = "onedark_dark",
    },
  },
}
