return {
  "folke/which-key.nvim",
  opts = {
    preset = "helix",
    defaults = {},
    plugins = {
      presets = {
        operator = false,
        motions = false,
        text_objects = false,
        windows = false,
        nav = false,
        z = false,
        g = false,
      },
    },
    icons = {
      mappings = false,
      separator = "->",
    },
    spec = {
      { mode = { "n" } },
      { "t", group = " LSP" },
      { "z", group = " Fold" },
      { "f", group = " Find" },
      { "g", group = " Goto" },
      { "s", group = " Search/Replace" },
      { "q", group = " Navigation" },
      { "<Leader>", group = " Leader" },
      { "<Leader>d", group = "DBUI" },
      { "<Leader>s", group = "Diffview open" },
      { "<Leader>c", group = "Macro" },
      { "<Leader><Tab>", group = "New tab" },
      { "gs", group = "Git stash/status" },
      { "ga", group = "Git add/restore" },
      { "gb", group = "Git checkout" },
      { "gl", group = "Git log" },
      { "gr", group = "Git reset/revert" },
      { "gd", group = "Git diff" },
      { "gp", group = "Git PR/misc" },
    },
    triggers = {
      { "t", mode = { "n" } },
      { "f", mode = { "n" } },
      { "g", mode = { "n" } },
      { "s", mode = { "n" } },
      { "z", mode = { "n" } },
      { "q", mode = { "n", "v", "o" } },
      { "<Leader>", mode = { "n" } },
    },
  },
  keys = false,
}
